apiVersion: v1
kind: Service
metadata:
  name: fleetman-api-gateway
  labels:
    app: fleetman
    component: api-gateway
spec:
  type: NodePort
  selector:
    app: fleetman
    component: api-gateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30020 
