apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
  labels:
    app: fleetman
    component: queue
spec:
  type: ClusterIP 
  selector:
    app: fleetman
    component: queue
  ports:
    - name: admin-port    
      protocol: TCP
      port: 8161
      targetPort: 8161    
    - name: messaging-port 
      protocol: TCP
      port: 61616
      targetPort: 61616 
