apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-simulator
  labels:
    app: fleetman
    component: position-simulator
spec:
  type: ClusterIP # Service interne pour la communication
  selector:
    app: fleetman
    component: position-simulator
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080