apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-position-tracker
  labels:
    app: fleetman
    component: position-tracker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fleetman
      component: position-tracker
  template:
    metadata:
      labels:
        app: fleetman
        component: position-tracker
    spec:
      containers:
        - name: position-tracker
          image: supinfo4kube/position-tracker:1.0.1
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "production-microservice"
          ports:
            - containerPort: 8080 # Port utilisé par l'API REST
