apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
  labels:
    app: fleetman
    component: queue
spec:
  type: ClusterIP
  selector:
    app: fleetman
    component: queue
  ports:
    - name: admin-port    # Nom du port pour l'administration
      protocol: TCP
      port: 8161
      targetPort: 8161    # Port exposé pour l'administration
    - name: messaging-port # Nom du port pour les messages
      protocol: TCP
      port: 61616
      targetPort: 61616   # Port utilisé par ActiveMQ pour les messages