apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-mongodb
  labels:
    app: fleetman
    component: mongo
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: fleetman
      component: mongo
  template:
    metadata:
      labels:
        app: fleetman
        component: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:3.6.23 
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db 
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo-data  
