apiVersion: v1
kind: Service
metadata:
  name: fleetman-web-app
  labels:
    app: fleetman
    component: web-app
spec:
  type: NodePort # Service exposé pour un accès externe au cluster
  selector:
    app: fleetman
    component: web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080 # Expose le port 30080 pour un accès externe
