apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-position-simulator
  labels:
    app: fleetman
    component: position-simulator
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: fleetman
      component: position-simulator
  template:
    metadata:
      labels:
        app: fleetman
        component: position-simulator
    spec:
      containers:
        - name: position-simulator
          image: supinfo4kube/position-simulator:1.0.1
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "production-microservice" 
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
